site_name: fewrecipes.com
site_author: Frankois
copyright: "Copyright &copy; 2020 Frankois"
site_url: https://fewrecipes.com
repo_name: frankois/fewrecipes.github.io

nav:
    - Accueil: index.md
    - Recettes:
        - Brownie: recipes/brownie.md
        - Quiche: recipes/quiche.md
        - Canneloni: recipes/canneloni.md
        - Lasagnes: recipes/lasagnes.md
        - Pizza: recipes/pizza.md
        - Chou-fleur paprika: recipes/chou_fleur_paprika.md 
        - Velouté chou-fleur: recipes/veloute_chou_fleur.md
        - Velouté courgette: recipes/veloute_courgette.md
        - Velouté lentille: recipes/veloute_lentille_corail.md

    - About: about.md

theme:
    name: journal
    custom_dir: custom_theme/

extra_css:
    - css/extra.css