site_name: fewrecipes.com
site_author: Frankois
copyright: "Copyright &copy; 2021 Frankois"
site_url: https://fewrecipes.com
repo_name: frankois/fewrecipes.github.io

nav:
    - Accueil: index.md
    - Recettes:
        - Brownie: recipes/brownie.md
        - Quiche: recipes/quiche.md
        - Canneloni: recipes/canneloni.md
        - Lasagnes: recipes/lasagnes.md
        - Pizza: recipes/pizza.md
        - Poulet pané: recipes/poulet_pane.md
        - Dahl lentilles: recipes/dahl_lentilles_corail.md
        - Chou-fleur paprika: recipes/chou_fleur_paprika.md
        - Chou-fleur coco: recipes/chou_fleur_coco_curry.md
        - Velouté chou-fleur: recipes/veloute_chou_fleur.md
        - Velouté courgette: recipes/veloute_courgette.md
        - Velouté lentille: recipes/veloute_lentille_corail.md
        - Bechamel: recipes/bechamel.md
        - Cookies parmesan: recipes/cookies_parmesan.md
        - Confiture: recipes/confiture.md
        - Ratafia: recipes/ratafia.md
        - Vin chaud: recipes/vin_chaud.md

    - About: about.md

theme:
    name: journal
    custom_dir: custom_theme/

extra_css:
    - css/extra.css